title: Mind & Matter
description: Exploring the fascinating worlds of neuroscience and psychology
baseurl: ""
url: "https://phybrackets.github.io"
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

author:
  name: Shivam
  email: physhivam@gmail.com

show_excerpts: true
header_pages:
  - about.md
  - archive.md

minima:
  skin: auto
  social_links:
    - { platform: email, user_url: "mailto:physhivam@gmail.com" }

paginate: 5
paginate_path: "/page:num/"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    